Added support for arbitrary container registry.
ServiceWeaver/weaver-kube pull request #24
Opened 2023-06-23 16:48 UTC by mwhittaker

Recall that `weaver kube deploy` needs to build and upload a container image to some registry. Before this PR, `weaver kube deploy` uploaded images to Docker Hub. In PR #21, @giautm suggested we add support for arbitrary container registries. This PR implements his idea.

Specifically, the user provides a `registry` field inside the `"kube"` section of the config file. For example, given the following config file:

```toml
[serviceweaver]
binary = "./foo"

[kube]
registry = "my_username"
```

`weaver kube deploy` will run `docker push my_username/IMAGE:TAG`. The user can provide any registry that is compatible with `docker push`. Some examples:

- Docker Hub: `USERNAME`
- Google Artifact Registry: `LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY`
- GitHub Container Registry: `ghcr.io/NAMESPACE`

I would also love suggestions for a better name than "registry"!

2023-06-23 17:27 UTC, spetrovic77 commented
I looked at Docker Hub and GCP Artifacts registry. They both have a concept of a "repo", but they aren't aligned. Here are what they both consider repos:

# Docker Hub

`spetrovic77/foo:tag1`

* `spetrovic77/foo` is the repo that contains tag `tag1`

# GCP Artifacts Registry

`us-west1-docker.pkg.dev/my-project/foo/foo:tag1`

* `us-west1-docker.pkg.dev/my-project/foo` is the repository.
* The above repository contains the image `foo`, with tag `tag1`.

To make things worse, if I do `docker push spetrovic77/bar:tag2`, DockerHub will create the repo `bar` for me automatically, with the appropriate tag. If I do `docker push us-west1-docker.pkg.dev/my-project/bar/bar:tag2`, I get an error that the `bar` repository doesn't exist.

So to create a `weaver-kube` image,  I need to pass in `spetrovic77` for DockerHub, and `us-west1-docker.pkg.dev/dingo-gke-dev/repo` for Artifacts Registry. Then we append `/weaver-kube:tag` to both, and push. But those prefixes `spetrovic77` and `us-west1-docker.pkg.dev/dingo-gke-dev/repo` don't both correspond to a registry or a repo.

Can we ask the user to pass in `spetrovic77/foo` and `us-west1-docker.pkg.dev/dingo-gke-dev/foo/foo` in the config. And we call it the "image". Then we just append `:tag` to it and push. WDYT?

2023-06-23 17:29 UTC, mwhittaker commented
Ooooh nice. I like that a lot better. Let me make that change.

2023-06-24 02:30 UTC, giautm requested changes
Rename correct field

2023-06-24 02:30 UTC, giautm commented on cmd/weaver-kube/deploy.go
> +      registry = "docker.io/my_docker_hub_username/foo"
```suggestion
      image = "docker.io/my_docker_hub_username/foo"
```

2023-06-25 01:51 UTC, spetrovic77 approved these changes
Looks great. How many engineers does it take to ... 🤣

2023-06-26 20:39 UTC, merged